=== dupuyjs/AzPester/Source/Schemas/2021-04/schema.definition.json
{
    "id": "schema.definition",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Definition",
    "description": "Schema for Definition File",
    "type": "object",
    "required": [
        "$schema",
        "contentVersion",
        "contexts",
        "definition"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "contentVersion": {
            "type": "string",
            "pattern": "(^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$)",
            "description": "A 4 number format for the version number of this parameter file. For example, 1.0.0.0"
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        },
        "contexts": {
            "type": "object",
            "properties": {
                "default": {
                    "$ref": "#/definitions/context",
                    "required": [
                        "subscriptionId",
                        "resourceGroupName"
                    ]
                }
            },
            "additionalProperties": {
                "$ref": "#/definitions/context",
                "required": [
                    "subscriptionId"
                ]
            },
            "required": [
                "default"
            ]
        },
        "definition": {
            "type": "object",
            "properties": {
                "network": {
                    "$ref": "./Network/schema.network.json#/definitions/network"
                },
                "identity": {
                    "$ref": "./Identity/schema.identity.json#/definitions/identity"
                }
            },
            "additionalProperties": false
        }
    },
    "definitions": {
        "parameter": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "metadata": {
                    "type": "object",
                    "description": "Metadata for the parameter, can be any valid json object"
                }
            },
            "required": [
                "type"
            ],
            "additionalProperties": false
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "secureObject",
                "array"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        },
        "context": {
            "type": "object",
            "properties": {
                "subscriptionId": {
                    "type": "string",
                    "description": "Subscription Identifier"
                },
                "resourceGroupName": {
                    "type": "string",
                    "description": "Resource Group Name"
                }
            },
            "additionalProperties": false
        }
    }
}

=== dupuyjs/AzPester/Samples/microsoft.network/nsg-dmz-in-vnet/azpester/definition.json
{
    "$schema": "../../../../Source/Schemas/2021-04/schema.definition.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "virtualNetworkName": {
            "type": "string",
            "defaultValue": "First_ARM_VNet"
        },
        "addressPrefix": {
            "type": "string",
            "defaultValue": "10.0.0.0/16"
        },
        "FESubnetPrefix": {
            "type": "string",
            "defaultValue": "10.0.0.0/24"
        },
        "AppSubnetPrefix": {
            "type": "string",
            "defaultValue": "10.0.1.0/24"
        },
        "DBSubnetPrefix": {
            "type": "string",
            "defaultValue": "10.0.2.0/24"
        },
        "FENSGName": {
            "type": "string",
            "defaultValue": "FE_NSG"
        },
        "AppNSGName": {
            "type": "string",
            "defaultValue": "App_NSG"
        },
        "DBNSGName": {
            "type": "string",
            "defaultValue": "DB_NSG"
        },
        "location": {
            "type": "string"
        },
        "subscriptionId": {
            "type": "string"
        },
        "resourceGroupName": {
            "type": "string"
        }
    },
    "contexts": {
        "default": {
            "subscriptionId": "{parameters.subscriptionId}",
            "resourceGroupName": "{parameters.resourceGroupName}"
        }
    },
    "definition": {
        "network": {
            "virtualNetworks": [
                {
                    "name": "{parameters.virtualNetworkName}",
                    "location": "{parameters.location}",
                    "addressSpace": [
                        {
                            "addressPrefix": "{parameters.addressPrefix}"
                        }
                    ],
                    "subnets": [
                        {
                            "name": "FESubnet",
                            "addressPrefix": "{parameters.FESubnetPrefix}",
                            "networkSecurityGroup": {
                                "name": "{parameters.FENSGName}"
                            }
                        },
                        {
                            "name": "AppSubnet",
                            "addressPrefix": "{parameters.AppSubnetPrefix}",
                            "networkSecurityGroup": {
                                "name": "{parameters.AppNSGName}"
                            }
                        },
                        {
                            "name": "DBSubnet",
                            "addressPrefix": "{parameters.DBSubnetPrefix}",
                            "networkSecurityGroup": {
                                "name": "{parameters.DBNSGName}"
                            }
                        }
                    ]
                }
            ],
            "networkSecurityGroups": [
                {
                    "name": "{parameters.FENSGName}",
                    "location": "{parameters.location}",
                    "securityRules": [
                        {
                            "name": "rdp_rule",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": "3389",
                            "sourceAddressPrefix": "Internet",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 100,
                            "direction": "Inbound"
                        },
                        {
                            "name": "web_rule",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": "80",
                            "sourceAddressPrefix": "Internet",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 101,
                            "direction": "Inbound"
                        }
                    ]
                },
                {
                    "name": "{parameters.AppNSGName}",
                    "location": "{parameters.location}",
                    "securityRules": [
                        {
                            "name": "Allow_FE",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": "443",
                            "sourceAddressPrefix": "{parameters.FESubnetPrefix}",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 100,
                            "direction": "Inbound"
                        },
                        {
                            "name": "Block_RDP_Internet",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": "3389",
                            "sourceAddressPrefix": "Internet",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 101,
                            "direction": "Inbound"
                        },
                        {
                            "name": "Block_Internet_Outbound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "Internet",
                            "access": "Deny",
                            "priority": 200,
                            "direction": "Outbound"
                        }
                    ]
                },
                {
                    "name": "{parameters.DBNSGName}",
                    "location": "{parameters.location}",
                    "securityRules": [
                        {
                            "name": "Allow_App",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": "1433",
                            "sourceAddressPrefix": "{parameters.AppSubnetPrefix}",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 100,
                            "direction": "Inbound"
                        },
                        {
                            "name": "Block_FE",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "{parameters.FESubnetPrefix}",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 101,
                            "direction": "Inbound"
                        },
                        {
                            "name": "Block_App",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "{parameters.AppSubnetPrefix}",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 102,
                            "direction": "Inbound"
                        },
                        {
                            "name": "Block_Internet",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "Internet",
                            "access": "Deny",
                            "priority": 200,
                            "direction": "Outbound"
                        }
                    ]
                }
            ]
        }
    }
}

=== dupuyjs/AzPester/Samples/HubSpoke/definition.json
{
    "$schema": "../../Source/Schemas/2021-04/schema.definition.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "subscriptionId": {
            "type": "string"
        },
        "resourceGroupName": {
            "type": "string"
        },
        "vmSize": {
            "type": "string",
            "defaultValue": "Standard_A1_v2",
            "metadata": {
                "description": "The size for both Windows and Linux virtual machines."
            }
        },
        "hubNetwork": {
            "type": "object",
            "defaultValue": {
                "name": "vnet-hub",
                "addressPrefix": "10.0.0.0/20"
            }
        },
        "spokeNetwork": {
            "type": "object",
            "defaultValue": {
                "name": "vnet-spoke-one",
                "addressPrefix": "10.100.0.0/16",
                "subnetName": "snet-spoke-resources",
                "subnetPrefix": "10.100.0.0/16",
                "subnetNsgName": "nsg-spoke-one-resources"
            }
        },
        "spokeNetworkTwo": {
            "type": "object",
            "defaultValue": {
                "name": "vnet-spoke-two",
                "addressPrefix": "10.200.0.0/16",
                "subnetName": "snet-spoke-resources",
                "subnetPrefix": "10.200.0.0/16",
                "subnetNsgName": "nsg-spoke-two-resources"
            }
        },
        "vpnGateway": {
            "type": "object",
            "defaultValue": {
                "name": "vgw-gateway",
                "subnetName": "GatewaySubnet",
                "subnetPrefix": "10.0.2.0/27",
                "pipName": "pip-vgw-gateway"
            }
        },
        "bastionHost": {
            "type": "object",
            "defaultValue": {
                "name": "AzureBastionHost",
                "publicIPAddressName": "pip-bastion",
                "subnetName": "AzureBastionSubnet",
                "nsgName": "nsg-hub-bastion",
                "subnetPrefix": "10.0.1.0/29"
            }
        },
        "azureFirewall": {
            "type": "object",
            "defaultValue": {
                "name": "AzureFirewall",
                "publicIPAddressName": "pip-firewall",
                "subnetName": "AzureFirewallSubnet",
                "subnetPrefix": "10.0.3.0/26",
                "routeName": "r-nexthop-to-fw"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "northeurope"
        }
    },
    "contexts": {
        "default": {
            "subscriptionId": "{parameters.subscriptionId}",
            "resourceGroupName": "{parameters.resourceGroupName}"
        }
    },
    "definition": {
        "network": {
            "virtualNetworks": [
                {
                    "name": "{parameters.hubNetwork.name}",
                    "addressSpace": [
                        {
                            "addressPrefix": "{parameters.hubNetwork.addressPrefix}"
                        }
                    ],
                    "subnets": [
                        {
                            "name": "{parameters.azureFirewall.subnetName}",
                            "addressPrefix": "{parameters.azureFirewall.subnetPrefix}"
                        },
                        {
                            "name": "{parameters.bastionHost.subnetName}",
                            "addressPrefix": "{parameters.bastionHost.subnetPrefix}"
                        },
                        {
                            "name": "{parameters.vpnGateway.subnetName}",
                            "addressPrefix": "{parameters.vpnGateway.subnetPrefix}"
                        }
                    ],
                    "virtualNetworkPeerings": [
                        {
                            "name": "hub-to-spoke-one",
                            "remoteVirtualNetwork": {
                                "name": "{parameters.spokeNetwork.name}"
                            }
                        },
                        {
                            "name": "hub-to-spoke-two",
                            "remoteVirtualNetwork": {
                                "name": "{parameters.spokeNetworkTwo.name}"
                            }
                        }
                    ]
                },
                {
                    "name": "{parameters.spokeNetwork.name}",
                    "location": "{parameters.location}",
                    "addressSpace": [
                        {
                            "addressPrefix": "{parameters.spokeNetwork.addressPrefix}"
                        }
                    ],
                    "subnets": [
                        {
                            "name": "{parameters.spokeNetwork.subnetName}",
                            "addressPrefix": "{parameters.spokeNetwork.subnetPrefix}"
                        }
                    ],
                    "virtualNetworkPeerings": [
                        {
                            "name": "spoke-one-to-hub",
                            "remoteVirtualNetwork": {
                                "name": "{parameters.hubNetwork.name}"
                            }
                        }
                    ]
                },
                {
                    "name": "{parameters.spokeNetworkTwo.name}",
                    "location": "{parameters.location}",
                    "addressSpace": [
                        {
                            "addressPrefix": "{parameters.spokeNetworkTwo.addressPrefix}"
                        }
                    ],
                    "subnets": [
                        {
                            "name": "{parameters.spokeNetworkTwo.subnetName}",
                            "addressPrefix": "{parameters.spokeNetworkTwo.subnetPrefix}"
                        }
                    ],
                    "virtualNetworkPeerings": [
                        {
                            "name": "spoke-two-to-hub",
                            "remoteVirtualNetwork": {
                                "name": "{parameters.hubNetwork.name}"
                            }
                        }
                    ]
                }
            ]
        }
    }
}

=== dupuyjs/AzPester/Samples/NetworkSecurityGroup/definition.json
{
    "$schema": "../../Source/Schemas/2021-04/schema.definition.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "subscriptionId": {
            "type": "string"
        },
        "resourceGroupName": {
            "type": "string"
        },
        "spokeNetwork": {
            "type": "object",
            "defaultValue": {
                "name": "vnet-spoke-one",
                "subnetNsgName": "nsg-spoke-one-resources"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "northeurope"
        }
    },
    "contexts": {
        "default": {
            "subscriptionId": "{parameters.subscriptionId}",
            "resourceGroupName": "{parameters.resourceGroupName}"
        }
    },
    "definition": {
        "network": {
            "networkSecurityGroups": [
                {
                    "name": "{parameters.spokeNetwork.subnetNsgName}",
                    "location": "{parameters.location}",
                    "securityRules": [
                        {
                            "name": "bastion-in-vnet",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": [
                                "22",
                                "3389"
                            ],
                            "sourceAddressPrefix": "10.0.1.0/29",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 100,
                            "direction": "Inbound"
                        },
                        {
                            "name": "DenyAllInBound",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "destinationPortRange": [
                                "*"
                            ],
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 1000,
                            "direction": "Inbound"
                        }
                    ],
                    "defaultSecurityRules": [
                        {
                            "name": "AllowVnetInBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "VirtualNetwork",
                            "destinationAddressPrefix": "VirtualNetwork",
                            "access": "Allow",
                            "priority": 65000,
                            "direction": "Inbound"
                        },
                        {
                            "name": "AllowAzureLoadBalancerInBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "AzureLoadBalancer",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 65001,
                            "direction": "Inbound"
                        },
                        {
                            "name": "DenyAllInBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 65500,
                            "direction": "Inbound"
                        },
                        {
                            "name": "AllowVnetOutBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "VirtualNetwork",
                            "destinationAddressPrefix": "VirtualNetwork",
                            "access": "Allow",
                            "priority": 65000,
                            "direction": "Outbound"
                        },
                        {
                            "name": "AllowInternetOutBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "Internet",
                            "access": "Allow",
                            "priority": 65001,
                            "direction": "Outbound"
                        },
                        {
                            "name": "DenyAllOutBound",
                            "protocol": "*",
                            "sourcePortRange": "*",
                            "destinationPortRange": "*",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "*",
                            "access": "Deny",
                            "priority": 65500,
                            "direction": "Outbound"
                        }
                    ]
                }
            ]
        }
    }
}

=== dupuyjs/AzPester/Samples/RouteTable/definition.json
{
    "$schema": "../../Source/Schemas/2021-04/schema.definition.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "subscriptionId": {
            "type": "string"
        },
        "resourceGroupName": {
            "type": "string"
        },
        "azureFirewall": {
            "type": "object",
            "defaultValue": {
                "name": "AzureFirewall",
                "subnetName": "AzureFirewallSubnet",
                "subnetPrefix": "10.0.3.0/26",
                "routeName": "r-nexthop-to-fw"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "northeurope"
        }
    },
    "contexts": {
        "default": {
            "subscriptionId": "{parameters.subscriptionId}",
            "resourceGroupName": "{parameters.resourceGroupName}"
        }
    },
    "definition": {
        "network": {
            "routeTables": [
                {
                    "name": "{parameters.azureFirewall.routeName}",
                    "location": "{parameters.location}",
                    "routes": [{
                        "name": "{parameters.azureFirewall.routeName}",
                        "addressPrefix": "0.0.0.0/0",
                        "nextHopType": "VirtualAppliance",
                        "nextHopIpAddress": "10.0.3.4"
                    }]
                }
            ]
        }
    }
}

=== dupuyjs/AzPester/Samples/Network/private-dns-zone/azpester/definition.json
{
    "$schema": "../../../../Source/Schemas/2021-04/schema.definition.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "privateDnsZoneName": {
            "type": "string",
            "defaultValue": "contoso.com"
        },
        "vmRegistration": {
            "type": "bool",
            "defaultValue": true
        },
        "vnetName": {
            "type": "string",
            "defaultValue": "VNet1"
        },
        "vnetAddressPrefix": {
            "type": "string",
            "defaultValue": "10.0.0.0/16"
        },
        "subnet1Prefix": {
            "type": "string",
            "defaultValue": "10.0.0.0/24"
        },
        "subnet1Name": {
            "type": "string",
            "defaultValue": "App"
        },
        "subnet2Prefix": {
            "type": "string",
            "defaultValue": "10.0.1.0/24"
        },
        "subnet2Name": {
            "type": "string",
            "defaultValue": "Utility"
        },
        "location": {
            "type": "string"
        },
        "subscriptionId": {
            "type": "string"
        },
        "resourceGroupName": {
            "type": "string"
        }
    },
    "contexts": {
        "default": {
            "subscriptionId": "{parameters.subscriptionId}",
            "resourceGroupName": "{parameters.resourceGroupName}"
        }
    },
    "definition": {
        "network": {
            "virtualNetworks": [
                {
                    "name": "{parameters.vnetName}",
                    "location": "{parameters.location}",
                    "addressSpace": [
                        {
                            "addressPrefix": "{parameters.vnetAddressPrefix}"
                        }
                    ],
                    "subnets": [
                        {
                            "name": "{parameters.subnet1Name}",
                            "addressPrefix": "{parameters.subnet1Prefix}"
                        },
                        {
                            "name": "{parameters.subnet2Name}",
                            "addressPrefix": "{parameters.subnet2Prefix}"
                        }
                    ]
                }
            ],
            "privateDnsZones": [
                {
                    "name": "{parameters.privateDnsZoneName}",
                    "virtualNetworkLinks": [
                        {
                            "name": "{parameters.privateDnsZoneName}-link",
                            "registrationEnabled": true,
                            "virtualNetwork": {
                                "name": "{parameters.vnetName}"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
